version: '3.8'

services:
  grafana-prod:
    build: .
    image: grafana-prod
    user: "472:472"
    ports:
      - "127.0.0.1:10020:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage-lib:/var/lib/grafana
      - grafana-storage-etc:/etc/grafana
    container_name: grafana-prod
    restart: always

volumes:
  grafana-storage-lib:
  grafana-storage-etc:
